import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "react-toastify/ReactToastify.min.css";

const roboto = Roboto({ subsets: ["latin"], weight:"400" });

export const metadata: Metadata = {
  title: "Vini Galeria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
